### ISSUE TITLE
Juntar pdf do aluno e do professor

### ISSUE THREAD

**Issue by simas0** [simas0/Livro-Aberto-de-Matematica-texto-do-projeto-#107]
Eu preciso de uma solução não braçal para unir os dois pdfs abaixo:
 página 1 do professor página 1 do aluno, página 2 do professor, página 2 do aluno, etc (a numeração do livro do aluno recomeça quando se inicia o texto para o estudante.

[fracoes_v0_4.pdf](https://github.com/simas0/Livro-Aberto-de-Matematica-texto-do-projeto-/files/478725/fracoes_v0_4.pdf)
[livro_professor.pdf](https://github.com/simas0/Livro-Aberto-de-Matematica-texto-do-projeto-/files/478726/livro_professor.pdf)

Alguém poderia me ajudar?
@gutosurrex , @hjbortol

**Comment by augustoteixeira** [comment]
Olá,

Na pasta onde estamos fazendo o Latex, tem um script que faz isso, chama `join`.

O comando em linux é:

```
pdftk B=first_file.pdf A=second_file.pdf shuffle A B output final.pdf
```
