### ISSUE TITLE
Ao fechar a edição de seção, a Wiki volta para o início da página. Manter a posição na seção sendo editada.

### ISSUE THREAD

**Issue by simas0** [simas0/Livro-Aberto-de-Matematica-texto-do-projeto-#13]

**Comment by simas0** [comment]
Isso é o que mais atrapalha o trabalho de edição e elaboração. Uma solução parcial é aquela do @hjbortol que pede para salvar sem sair da janela de edição.

**Comment by hjbortol** [comment]
Estou redigindo atividades para a lição 2 e, de fato, este problema prejudica muito a concentração, principalmente quando estamos trabalhando com várias atividades. Reforço aqui então a situação crítica deste issue.

**Comment by augustoteixeira** [comment]
Olá, eu estou testando uma outra ferramenta que pode melhorar essa questão. Mas como ela vai ser um pouco mais complicada de implementar na wiki do livro, eu a implementei primeiro na [wiki do projeto](http://www.umlivroaberto.com/wiki)

Essa ferramenta basicamente permite edição _inline_. Assim, o colaborador realmente volta ao lugar correto sempre.

Vocês poderiam testar lá na wiki do projeto e dizer se ficou bom e vale a pena implementar na outra?

**Comment by hjbortol** [comment]
Augusto,

Tentei clicar em Editar na página

https://www.umlivroaberto.com/wiki/doku.php?id=discus:racionais

O sistema então mostra a imagem em anexo (uma barra de carregando) e não sai dela ...

Um abraço!

![dokuwiki-03](https://cloud.githubusercontent.com/assets/7694624/14573947/eeae4b8a-032e-11e6-8842-c29ceed46df6.jpg)

**Comment by augustoteixeira** [comment]
Confirmado, estava funcionando em algumas páginas mas não em outras.

Desinstalado e procurando outra alternativa...

**Comment by simas0** [comment]
Observo que este problema surgiu quando criamos a página de títulos com a finalidade de incluir diversos botões "Editar". Por exemplo, quando editamos e salvamos a seção Etapa do Ensino Médio na página [(https://www.umlivroaberto.com/wiki/doku.php?id=discus:projeto)] , somos direcionados para o link [https://www.umlivroaberto.com/wiki/doku.php?id=discus:projeto#etapa_ensino_medio] que nos mantém na mesma seção em que estávamos.

Não funciona simplesmente incluir o "#secao_editada" no final do endereço da página salva?

**Comment by augustoteixeira** [comment]
A solução que foi dada é a seguinte:

À partir de agora, ao terminar de editar uma página incluída não somos redirecionados para a lição e sim para o html da página incluída. Podemos por exemplo continuar editando. Quando nos damos por satisfeitos, existe um link no canto superior direito que nos manda de volta para a lição no ponto correspondente à seção incluída.

Caso queiram reportar bugs ou pedir melhorias, favor abrir outra issue e colocar uma prioridade compatível.

**Comment by hjbortol** [comment]
O código necessário para este sistema funcionar vai ser gerado automaticamente, ou a cada seção aberta será preciso fazer a inclusão manualmente? Obrigado!

{{anchor:chave_de_caixa}} (na página da Lição)

;;#
Ir para [[cap4:texto#problema_motivador]]
;;#  (dentro da atividade)

**Comment by augustoteixeira** [comment]
Por enquanto o código precisa ser introduzido manualmente (como eu fiz para todas as páginas ontem).
Lembrem que existe um pedaço de código que deve ser incluído na lição também, junto ao include.

Se isso estiver chato vocês podem introduzir uma issue pra eu tentar automatizar isso.
