### ISSUE TITLE
pdf com apenas o conteúdo para o aluno 

### ISSUE THREAD

**Issue by simas0** [simas0/Livro-Aberto-de-Matematica-texto-do-projeto-#15]

**Comment by augustoteixeira** [comment]
Feito!

**Comment by simas0** [comment]
O pdf do aluno não deveria conter as respostas das atividades.

**Comment by simas0** [comment]
Além disso,  no pdf do estudante não deveria entrar qualquer coisa que no código esteja dentro do <hidden asdas> nem coisas com código tipo
/\* sdasdasd */

**Comment by augustoteixeira** [comment]
Resposta foi tirado.
Quanto a /\* blablabla */, a única ocorrência que eu vi erra um erro de sintaxe (ou seja, tinha algo na sintaxe que o dokuwiki resolveu aceitar mas não o conversor pra tex). Você poderia dar um exemplo? Senão favor fechar a issue.

**Comment by augustoteixeira** [comment]
Outra coisa. Quando for assim, é melhor outra issue. A questão do pdf pro aluno foi feita, mas os bugs dela são uma outra coisa.
