### ISSUE TITLE
Inserir numeração nos exercícios na Wiki

### ISSUE THREAD

**Issue by simas0** [simas0/Livro-Aberto-de-Matematica-texto-do-projeto-#18]
Esta numeração deve ser a mesma do pdf.

**Comment by augustoteixeira** [comment]
Está implementado da seguinte forma:

Na página onde escrevemos a atividade, não colocamos nenhum título. O texto inicia diretamente.

Na página principal da Lição (aquala que inclui todas as atividades e outros arquivos) colocamos antes de incluir cada atividade o seu título da seguinte forma:

===== - Atividade =====

antes de {{page>cap1:atividade...

**Comment by simas0** [comment]
A numeração está "1 Atividade", mas o esperado é "Atividade 1".

**Comment by augustoteixeira** [comment]
Continua com alta prioridade?

**Comment by augustoteixeira** [comment]
Toda hora eu entro nesse issue achando que já resolvi (por conta do título)... Nesses casos temos que abrir outra issue.
