### ISSUE TITLE
Criar <hidden Comentários> automaticamente após cada parágrafo do livro texto que abre um Fórum.

### ISSUE THREAD

**Issue by simas0** [simas0/Livro-Aberto-de-Matematica-texto-do-projeto-#20]
Isto traria barreira praticamente zero para colaborações externas. Isso foi feito em [(http://book.realworldhaskell.org/read/web-site-and-comment-system-usage-and-policies.html)] e provavelmente trata-se de um script simples em java.

**Comment by simas0** [comment]
Posso criar expectativas quanto à implementação disso?

**Comment by augustoteixeira** [comment]
Pode, hehe...

**Comment by augustoteixeira** [comment]
Feito. Crie uma página nova e veja se é assim que você estava pensando.

**Comment by simas0** [comment]
Não era isso. Era como no link que enviei. Lá o colaborador pode fazer sugestões e comentários num campo de texto que não altera o html, não tem que concordar com termos, cessão de direitos, nada disso. Seria realmente apenas o custo de um clique e começar a escrever. 

O @hjbortol, por exemplo, acha que do modo como estamos fazendo teremos poucas contribuições da comunidade. Do jeito do Real World Haskell as chances de não haver colaborações caem muito.

**Comment by simas0** [comment]
Conforme conversamos hoje uma possibilidade é que após a criação de uma página qualquer na lição, crie-se automaticamente uma página de comentários de livre edição pela comunidade. Por exemplo,
Após o elaborador criar a página

```
===== - Atividade =====
{{page>cap2:secoes:atividade_poder_da_notacao}}

```

Pode-se criar automaticamente uma página 
`{{page>cap2:secoes:atividade_poder_da_notacao_comentarios}}
`
contendo:

```
<hidden Comentários>
Use este espaço para observações sobre o texto acima. Por favor, não apague os comentários de outros usuários e use o <a href="  ">fórum</a> para enviar sugestão de atividades.
</hidden>
```

**Comment by augustoteixeira** [comment]
Feito
