### ISSUE TITLE
Imagens in-line na Wiki

### ISSUE THREAD

**Issue by hjbortol** [simas0/Livro-Aberto-de-Matematica-texto-do-projeto-#21]
@gutosurrex: permitir que imagens apareçam no meio de uma sentença em um parágrafo na WikiA

**Comment by simas0** [comment]
Veja atividade 6 na lição 1 para exemplos do que é necessário ser possível fazer. Isto está empacando o prosseguimento da lição 1 para revisão

**Comment by augustoteixeira** [comment]
Já está funcionando, mas tem que usar a notação correta. Veja na atividade 6 da lição 1 para entender como funciona.
