### ISSUE TITLE
Renomear rótulos das seções na Wiki

### ISSUE THREAD

**Issue by hjbortol** [simas0/Livro-Aberto-de-Matematica-texto-do-projeto-#22]
@gutosurrex  e @simas0, existe uma maneira simples de renomear os rótulos das seções na Wiki? Por exemplo,  para o rótulo

{{page>cap1:secoes:atividade7}}

cujo nome aparece atividade7 está a Atividade 5. Esta dúvida é da Estela ...

**Comment by simas0** [comment]
Não. Mudar o nome de uma página gera links quebrados. Por isso, o ideal é que se crie outra página com outro nome copie e cole o conteúdo da primeira. Sugiro não mais usar numeração para nomear as atividades.

**Comment by augustoteixeira** [comment]
Existe um plugin que permite renomear páginas

**Comment by augustoteixeira** [comment]
Eu instalei e devemos fazer o seguinte:
- ir no índice de páginas (canto superior direito)
- navegar para a página desejada
- olhar na barra à direita, depois de editar, revisões e links, temos renomear

Aprecie com moderação
