### ISSUE TITLE
Organização das lições

### ISSUE THREAD

**Issue by hjbortol** [simas0/Livro-Aberto-de-Matematica-texto-do-projeto-#24]
@gutosurrex e @simas0, pedidos da coordenadora Estela: cada lição tem divisões que foram definidas anteriormente (Explorando, Conexões, ...). Assim:

(1) Dar mais destaques a estas divisões (fonte maior, linha separando, algo do tipo)

(2) Na lição 1, esta divisão está misturada. Por exemplo, existem três atividades com explorando dentro de cada uma delas, enquanto que o que deve ocorrer é o contrário.

Um abraço!

**Comment by augustoteixeira** [comment]
Não entendi bem... não podemos simplesmente usar:

==== - Atividade ====

<WRAP explorando>
</WRAP>

Atualmente, se for feito o contrário (isto é, colocar a atividade dentro do WRAP), ela não será numerada corretamente.

**Comment by simas0** [comment]
@hjbortol , eu criei páginas apenas contendo os títulos para as seções de exercícios (EXPLORANDO O ASSUNTO e MÃO NA MASSA). Em CONEXÕES e PARA REFLETIR há texto próprio das seções, então os textos vão nas respectivas páginas. Além disso eu coloquei as seções com o mesmo destaque do título Lição. Para isso basta usar 6 iguais, por exemplo, ====== CONEXÕES ======.

Também mudei os nomes das páginas de atividades que foram nomeadas com numeração, por exemplo: cap1:secoes:atividade7, mudei para algo como cap1:secoes:ativ_identif_tercos. O problema é não deixar estes nomes numerados continuarem a ser propagados na Lição 3.

Abraço!
