### ISSUE TITLE
Como fazer listas dentro de listas na Wiki? É possível continuar a numeração depois?

### ISSUE THREAD

**Issue by hjbortol** [simas0/Livro-Aberto-de-Matematica-texto-do-projeto-#27]
Como fazer listas dentro de listas na Wiki?

É possível continuar a numeração depois?

**Comment by augustoteixeira** [comment]
Isso é parte da sintaxe da wiki. É isso o que você estava pensando?

https://www.dokuwiki.org/wiki:syntax#lists

Se não for, reabra a issue com uma explicação melhor.

**Comment by simas0** [comment]
Acho que o @hjbortol queria perguntar como continuar a numeração como no exemplo abaixo:

   UM. primeiro tópico desta lista
   DOIS. segundo tópico desta lista
   TRÊS. terceiro tópico desta lista

 Quero detalhar mais o tericeiro tópico neste ponto, colocar outros itens como no exemplo da sintaxe

```
             a. primeiro tópico da nova lista

             b. segundo tópico da nova lista
```

  QUATRO. quarto tópico desta lista (AQUI ESTÁ O PROBLEMA. NÃO CONSEGUIMOS RETOMAR A NUMERAÇÃO, CERTO @hjbortol ? Se sim, reabra a pergunta, por favor)

**Comment by hjbortol** [comment]
Olá Augusto e Fábio!

Com relação a listas dentro de listas, ok!

Com relação a continuar a numeração, é o que Fábio descreveu:

(1) Item aqui
(2) Item aqui

Comentários aqui.

(3) A numeração continua aqui!

Obrigado!

**Comment by augustoteixeira** [comment]
Uma possibilidade é fazer o seguinte

```
- primeiro ítem,
- segundo ítem,\\ comentários aqui
- terceiro ítem.
```

Feche se isso for suficiente.

**Comment by hjbortol** [comment]
Augusto,

Acho que não me expressei bem.  Aqui está um exemplo concreto do livro: tem uma história da divisão de 2 barras de chocolate entre 3 irmãs. Faço perguntas sobre a equipartição. Assim:

História das 3 irmãs.

(1) Pergunta da história.
(2) Pergunta da história.

Agora, um texto, modificando a história: uma das irmãs deu sua parte do chocolate para outra irmã.

(3) Pergunta da continuação da história.
(4) Pergunta da continuação da história.

Texto explicando a continuação da história: uma irmã divide o que tem entre outras duas.

(5) Pergunta da continuação da história.
(6) Pergunta da continuação da história.

Um abraço!

**Comment by augustoteixeira** [comment]
Olá Humberto,

Eu acho que eu entendi sim. Eu implementei a minha sugestão acima com o texto que você enviou. Veja no [link](https://www.umlivroaberto.com/livro/doku.php?id=sandbox).

Se estiver bom, feche o issue.

**Comment by hjbortol** [comment]
Está ótimo! Obrigado!
