### ISSUE TITLE
Algumas caixas <WRAP professor> ou <WRAP imagem> funcionam no pdf outras não.

### ISSUE THREAD

**Issue by simas0** [simas0/Livro-Aberto-de-Matematica-texto-do-projeto-#29]
No pdf aparece uma mensagem de erro.

**Comment by augustoteixeira** [comment]
Eu tentei melhorar bastante isso... Tente mostrar um exemplo específico em que não funciona.

**Comment by simas0** [comment]
Parece que está tudo funcionando. Obrigado!
