### ISSUE TITLE
Acesso ao html do livro por celular - Espaço na tela

### ISSUE THREAD

**Issue by simas0** [simas0/Livro-Aberto-de-Matematica-texto-do-projeto-#33]
Nas caixas, "Para o professor", "Imagem", "Resposta", etc. A imagem ao lado do título move todo o texto da caixa para a direita tornando a visualização difícil em telas pequenas e aumentando o tamanho vertical da caixa e da página. Sugiro retirar estas figuras ou dar outra solução para que não ocupem tanto espaço vertical da caixa.

**Comment by augustoteixeira** [comment]
Feito!
