### ISSUE TITLE
Tela em branco ao salvar uma atualização

### ISSUE THREAD

**Issue by hjbortol** [simas0/Livro-Aberto-de-Matematica-texto-do-projeto-#34]
Ao salvar uma atualização, o sistema leva para uma tela em branco. Ao recarregar a página, o navegador diz que é preciso reenviar os dados. Ao aceitar, a página é atualizada. Esta tela em branco intermediária não aparecia antes.

**Comment by simas0** [comment]
Estou experimentando o mesmo erro.

**Comment by augustoteixeira** [comment]
Acho que está bem agora...

**Comment by augustoteixeira** [comment]
me digam se continuarem com problemas
