### ISSUE TITLE
No pdf do aluno não deveria aparecer o texto que no código está dentro do <hidden> </hidden>

### ISSUE THREAD

**Issue by simas0** [simas0/Livro-Aberto-de-Matematica-texto-do-projeto-#35]
No pdf do professor deveria aparecer apenas o texto que está dentro de hidden Para o professor e hidden Resposta. Os demais devem ser omitidos. Se facilitar podemos limitar os tipos de hidden xyz que surgem.

**Comment by augustoteixeira** [comment]
Estabelecer prioridade

**Comment by simas0** [comment]
Mudei a prioridade porque isso já não é mais necessário nas lições 1 e 2 e não estão sendo muito mais utilizados os hiddens Comentário.

**Comment by simas0** [comment]
Acho que isso foi feito, certo?

**Comment by augustoteixeira** [comment]
O que acontece agora é o seguinte. Todos os comandos "hidden" são ignorados. Como você disse que eles somente são utilizados para as seções "Para o professor" e "resposta", então de fato eles ficam de fora do livro do aluno.
