### ISSUE TITLE
Figuras no pdf devem ter o mesmo tamanho que no html

### ISSUE THREAD

**Issue by simas0** [simas0/Livro-Aberto-de-Matematica-texto-do-projeto-#41]
As figuras no pdf estão com tamanho fixo (altura igual a 4 cm, talvez?). Precisamos que o seu tamanho no pdf seja o mesmo do código da DokuWiki.

**Comment by hjbortol** [comment]
Depois que os templates TeX e CSS/HTML estiverem pronto, acho que vamos ter uma ideia melhor de como calibrar as dimensões da DokuWiki em função de como a imagem ficará nestes ambientes.

**Comment by simas0** [comment]
Alterei a prioridade porque este problema juntamente com o das tabelas não reconhecidas no pdf dificultam o teste do material.

**Comment by augustoteixeira** [comment]
Feito!
