### ISSUE TITLE
Numeração das Atividades no pdf está diferente da numeração da DokuWiki

### ISSUE THREAD

**Issue by simas0** [simas0/Livro-Aberto-de-Matematica-texto-do-projeto-#44]
Isso acontece porque as atividades são convertidas em \section para o .tex. Mas deveriam ser convertidas para um ambiente próprio com numeração própria (\begin{atividade})

Temos prioridade alta em tudo o que é necessário ao pdf funcionar bem.

**Comment by augustoteixeira** [comment]
Feito!
