### ISSUE TITLE
Notação matemática desaparece no arquivo em latex

### ISSUE THREAD

**Issue by simas0** [simas0/Livro-Aberto-de-Matematica-texto-do-projeto-#45]
Na Lição 2 no início da lição temos quadrinhos, na descrição do Quadrinho 3 os símbolos matemáticos desaparecem quando vão para o arquivo em latex.

Por exemplo, em 
meio $\longrightarrow \frac{1}{2}$

somente aparece "meio".

**Comment by simas0** [comment]
O mesmo acontece na resposta das Atividades 8 e 10, numeração do html (12 e 14 no pdf).

**Comment by augustoteixeira** [comment]
Feito :)
