### ISSUE TITLE
O ambiente Resposta não deveria ser numerado no pdf

### ISSUE THREAD

**Issue by simas0** [simas0/Livro-Aberto-de-Matematica-texto-do-projeto-#47]

**Comment by augustoteixeira** [comment]
Agora só atividades estão numeradas no pdf, fica bom? Estou fechando por hora.

**Comment by simas0** [comment]
Não é isso que vejo nos pdfs... Parece que as mudanças não estão chegando ao pdf gerado automaticamente... As imagens, respostas, notas, todas possuem numeração.

**Comment by augustoteixeira** [comment]
Desculpe, eu tinha feito só no meu computador. Agora deve estar funcionando geral.
