### ISSUE TITLE
A numeraçao na DokuWiki não funciona sempre bem no pdf

### ISSUE THREAD

**Issue by simas0** [simas0/Livro-Aberto-de-Matematica-texto-do-projeto-#48]
Na Lição 1 todas as numerações estão com problema até a da atividade 15.

**Comment by augustoteixeira** [comment]
Acho que agora está bom. Estou fechando por hora, mas se você achar que não funcionou reabra e seja mais específico.

**Comment by simas0** [comment]
Veja a numeração dos itens da Atividade 1 da Lição 1 no pdf (link abaixo). São todos 1., embora na DokuWiki estejam corretos.

[(https://www.umlivroaberto.com/pdf/cap1_aluno.pdf)]

**Comment by augustoteixeira** [comment]
Ahhh... achei que você estava falando da numeração de seções. Pelo visto é de enumerate, certo?

Eu acho que o problema é que a galera está colocando \ no fim de cada linha do enumerate (sem necessidade). Por exemplo, na atividade 1 isso resolveu com:
https://www.umlivroaberto.com/livro/doku.php?id=cap1:secoes:ativ_equiparticao&do=diff&rev2[0]=1463682278&rev2[1]=1464398415&difftype=sidebyside

Reabra se achar que ainda está com problema (e inclua detalhes).

**Comment by simas0** [comment]
Na Atividade 2 também resolveu com a retirada de \, mas ainda na Atividade 1 o enumerate reiniciou após o ambiente figure (veja o item 4) e na Atividade 6 o enumerate reiniciou em cada item, acredito que seja porque há figuras inline. Não sei como resolver.

**Comment by augustoteixeira** [comment]
Galera, vamos adquirir o hábito: Se eu entendi bem, acho que essa questão está fechada e o que você está mencionando agora é um outro problema: quando se cria uma figura inline dentro do enumerate, perde-se a numeração.

Se for esse mesmo o caso, o certo é abrir outra issue. E o mais importante, com o nível correto de prioridade.
