### ISSUE TITLE
pdf não reconhece tabelas da Dokuwiki

### ISSUE THREAD

**Issue by simas0** [simas0/Livro-Aberto-de-Matematica-texto-do-projeto-#49]
Veja o exemplo da primeira atividade do Mão na Massa da Lição 2.

**Comment by simas0** [comment]
Isto gera todos os problemas de figuras inexistentes no pdf da lição 2 porque as figuras estão dentro de tabelas.

**Comment by simas0** [comment]
Mudei a prioridade porque a Lição 3 será finalmente entregue e esse problema, junto com o do tamanho das figuras nos impede de testar o material.

**Comment by augustoteixeira** [comment]
Ufff... esse deu trabalho.
