### ISSUE TITLE
<WRAP professor> não funciona bem no pdf em algumas atividades da Lição 2.

### ISSUE THREAD

**Issue by simas0** [simas0/Livro-Aberto-de-Matematica-texto-do-projeto-#50]
Ver atividades 5, 18 e 21 da Lição 2 no pdf do professor.
( ERRO:<WRAP) professor> 

O código parece certo na DokuWiki.

**Comment by augustoteixeira** [comment]
Cara, a minha teoria é que existe algum erro de sintaxe em cada um desses WRAPS. Eu chequei o primeiro e encontrei uma aspas unicode que não passa pelo conversor (já tentei consertar isso, mas parece chato).

Ao consertar essas aspas, o pdf passou a funcionar:
https://www.umlivroaberto.com/livro/doku.php?id=cap2:secoes:atividade_tortas_improprias&do=diff&rev2[0]=1463860742&rev2[1]=1464010301&difftype=sidebyside

Será que não é sempre algo desse tipo? Temos que discutir como lidar com essas coisas.

**Comment by simas0** [comment]
O problema realmente eram as aspas de texto com outra codificação.
