### ISSUE TITLE
Aspas criam espaço quando passam para o pdf

### ISSUE THREAD

**Issue by simas0** [simas0/Livro-Aberto-de-Matematica-texto-do-projeto-#57]
O texto:
"metade de" e "um meio de" 
ganha um espaços entre o abre aspas e a primeira palavra tornando-se
" metade de" e " um meio de"

Veja o primeiro Para o professor da lição 1.
[https://www.umlivroaberto.com/pdf/cap1.pdf]

**Comment by augustoteixeira** [comment]
Corrigido!
