### ISSUE TITLE
Figuras reiniciam a numeração no pdf

### ISSUE THREAD

**Issue by simas0** [simas0/Livro-Aberto-de-Matematica-texto-do-projeto-#58]
Ver lição 1 atividades 1, 6, 7 e 8 para exemplos.
[https://www.umlivroaberto.com/pdf/cap1.pdf]

**Comment by augustoteixeira** [comment]
Figuras inseridas (em um enumerate) reiniciam a numeração (do enumerate). Confirmado.

**Comment by simas0** [comment]
As figuras reiniciam mesmo que não estejam dentro do ambiente `<WRAP imagem>`

**Comment by augustoteixeira** [comment]
Agora só dá problema quando está dentro do ambiente `<WRAP imagem>`, o que a princípio não vai existir na versão final, correto?
