### ISSUE TITLE
Aumentar espaçamento antes e depois de títulos no pdf

### ISSUE THREAD

**Issue by simas0** [simas0/Livro-Aberto-de-Matematica-texto-do-projeto-#59]
Antes e depois dos títulos Explorando o Assunto, Organizando as Ideias, Mão na Massa e Quebrando a Cuca. Na verdade eles aparecem como texto em negrito e grande no latex, sugiro que sejam seções sem numeração. Isso deve automatizar essas mudanças.
[https://www.umlivroaberto.com/pdf/cap1.pdf]

**Comment by augustoteixeira** [comment]
Feito!
