### ISSUE TITLE
Moderação dos comentários na DouWiki.

### ISSUE THREAD

**Issue by simas0** [simas0/Livro-Aberto-de-Matematica-texto-do-projeto-#62]
Eu gostaria de poder excluir (e talvez editar) os comentários realizados por outros usuários na DokuWiki (através do plugin). Isso será especialmente útil porque os comentários se tornam desatualizados ou inúteis (podendo causar confusão) após edição do texto.

**Comment by augustoteixeira** [comment]
With great power, comes great responsibility.

Eu te dei direitos de semi-administrador. Preste bastante atenção com sua senha à partir de agora!

**Comment by hjbortol** [comment]
A Wiki guarda versões anteriores do conteúdo. Ela também guarda versões anteriores dos comentários, isto é, dá para acessar versões anteriores com os comentários originais?

**Comment by augustoteixeira** [comment]
Ficam guardadas, mas de maneira difícil de acessar. Podemos usar os emails enviados pra buscar, mas ainda não é uma boa solução... se for útil, abram um issue que eu penso em como implementar.
