### ISSUE TITLE
As figuras não aparecem no html, no lugar ficam apenas os links para as mesmas

### ISSUE THREAD

**Issue by simas0** [simas0/Livro-Aberto-de-Matematica-texto-do-projeto-#63]
Já tinha observado este problema ontem em algumas páginas novas, mas agora vejo no início da Lição 1.
Observando as edições anteriores do arquivo vejo o mesmo problema. Parece ser uma instabilidade da DokuWiki e não problema no código. Talvez tenha alguma correlação com o plugin de comentários pois o problema aqui relatado começou logo após novos comentários serem postados.

**Comment by simas0** [comment]
@hjbortol sugere que isso acontece com as figuras em formato PNG, para o caso de ajudar na solução do problema.

**Comment by augustoteixeira** [comment]
Resolvido. Mas vamos evitar mandar imagens de mais de 400k para a wiki, pois isso está causando muita lentidão pra abrir as páginas.

**Comment by hjbortol** [comment]
Os arquivos de imagem estão grandes para ter uma resolução maior. Mas como acredito que todas as figuras vão ser refeitas no final das contas, vou enviá-las com resolução mais baixa. Aliás, isto vai ser uma questão que teremos que considerar em algum momento: para a versão em PDF, o ideal é ter figuras no formato vetorial mas, por enquanto, só estamos produzindo imagens bitmap.

**Comment by augustoteixeira** [comment]
Com certeza, no pdf vai ser vetorial e bonitinho. Já estamos olhando alguém pra fazer.

Por agora, se a figura enviada for jpg, ela vai ser comprimida automaticamente, mas não as figuras png. É melhor mandar png já bem pequena, ou usar sempre jpg.

**Comment by hjbortol** [comment]
Augusto, então as figuras PNG vão ficar sempre como links? Não dá para o downscale ser feito automaticamente para PNG também ou, então, converter todos os PNG já existentes para JPG? Eu sou eu que vou ter que fazer isto?

**Comment by augustoteixeira** [comment]
Não, as figuras png já estão aparecendo de novo... mas eu tenho que fazer o downscale delas manualmente por enquanto.

**Comment by hjbortol** [comment]
Vou enviar só em JPG agora ...
