### ISSUE TITLE
Texto da Lição 2 ficou em itálico

### ISSUE THREAD

**Issue by hjbortol** [simas0/Livro-Aberto-de-Matematica-texto-do-projeto-#64]
Por algum motivo, todo o texto da Lição 2 está em itálico agora.

@simas0

**Comment by simas0** [comment]
Não era bug. A Cydara editou a Atividade 1 e incluiu // no final do último item por algum motivo, isso deixou todo o texto da sequência em itálico. Resolvido. Favor informar se identificar este problema em outro ponto.
