### ISSUE TITLE
Figuras PNG não aparecem nas lições (apenas como links)

### ISSUE THREAD

**Issue by hjbortol** [simas0/Livro-Aberto-de-Matematica-texto-do-projeto-#65]
Nas lições, as figuras PNG aparecem como link, enquanto que as figuras JPG são exibidas normalmente. Isto é proposital? Penso que todas as figuras deveriam ser exibidas.

@simas0

**Comment by simas0** [comment]
Duvido que seja proposital. Eu já havia identificado este problema, coloquei como Emergência. Estou fechando este chamado.
