### ISSUE TITLE
Os comentários na DokuWiki não estão sendo enviados por e-mail para o Humberto nem para a Estela.

### ISSUE THREAD

**Issue by simas0** [simas0/Livro-Aberto-de-Matematica-texto-do-projeto-#67]
Imagino que também não estão indo para a Cydara nem para o Cataldo.

**Comment by augustoteixeira** [comment]
Acabei de reenviar os convites (eles tem que aceitá-los). É um email enviado pelo grupo umlivroaberto.wiki@googlegroups.com com a frase:

Aceite este convite para participar do Grupo do Google um-livro-aberto.
