### ISSUE TITLE
Criar repositório para figuras geométricas

### ISSUE THREAD

**Issue by simas0** [simas0/Livro-Aberto-de-Matematica-texto-do-projeto-#68]
E inserir link para elas na página correspondente. Precisamos disso para entregar ao Cláudio e pedir para ele divulgar entre os estudantes da obmep.

**Comment by augustoteixeira** [comment]
Você poderia explicar melhor o que deve ser feito?

**Comment by simas0** [comment]
Preciso de uma pasta no servidor, para onde os estudantes da OBMEP possam subir os arquivos sem necessidade de login ou senha. O ideal é que eles possam colocar apenas arquivos nos formatos SVG e TICZ e não possam apagar. Também seria muito bom se fosse enviado um e-mail quando algum arquivo entrar na pasta.

**Comment by hjbortol** [comment]
Como vai ficar a logística de acesso do texto a estas figuras? Haverá algum tipo de regra para a composição do nome do arquivo?

**Comment by simas0** [comment]
Sim @hjbortol, veja em [(https://www.umlivroaberto.com/livro/doku.php?id=figuras_geometricas)]

**Comment by hjbortol** [comment]
Numerar a atividade talvez não seja uma boa, pois a ordem pode eventualmente mudar. Talve o melhor fosse usar o rótulo que está sendo empregado para edição (por exemplo, para a Atividade 1 da Lição 1: cap1:secoes:ativ_equiparticao). O que acham?

**Comment by simas0** [comment]
@hjbortol , você tem razão. Fiz como você sugeriu.

**Comment by simas0** [comment]
@hjbortol, poderia, por favor, conferir se as figuras em "barra" e "salgadas" da Lição 2 que eu chamei de geométricas, são realmente geométricas ou você prefere que sejam figuras artísticas?

**Comment by hjbortol** [comment]
Eu prefiro que sejam geométricas!

**Comment by augustoteixeira** [comment]
Cara, está feito. no próprio [https://www.umlivroaberto.com/livro/doku.php?id=figuras_geometricas]. Não é ideal, mas agora pessoas podem fazer sign up na wiki do livro e terão acesso a essa página e todas linkadas lá dentro, onde podem postar o código tikz. Quanto a renderização, pode ser automatizada depois.
