### ISSUE TITLE
Como colocar um texto dentro de uma caixa?

### ISSUE THREAD

**Issue by hjbortol** [simas0/Livro-Aberto-de-Matematica-texto-do-projeto-#70]
Para a resposta da Atividade 10 (https://www.umlivroaberto.com/livro/doku.php?id=cap4:texto#equivalencia_complete_os_quadrados), preciso colocar números dentro de uma caixa (os quadradinhos). Como fazer?

**Comment by augustoteixeira** [comment]
É só usar $\fbox{4}$. Veja por exemplo em:
https://www.umlivroaberto.com/livro/doku.php?id=sandbox

**Comment by hjbortol** [comment]
Eu gostaria de manter as caixas todas com mesma largura (de forma que a caixa de 123 tenha a mesma largura que  a caixa de 1), mas acho que não preciso me preocupar com isto agora, não é?

**Comment by simas0** [comment]
O ideal seria deixar isso arrumado. Dá para fazer usando espaçamento e notação matemática. @gutosurex,  tikz aqui viria a calhar... @hjbortol, já abriu esse issue?

**Comment by augustoteixeira** [comment]
Ainda não entendi bem...

A primeira coisa que deveríamos fazer é aumentar os quadrados para o aluno deixar suas respostas. Os quadrados gerados por \square são muito pequenos pro aluno poder escrever dentro.

De qualquer forma, essas mudanças podem ser feitas puramente no latex.
