### ISSUE TITLE
As aspas no pdf do aluno estão como no código tex

### ISSUE THREAD

**Issue by simas0** [simas0/Livro-Aberto-de-Matematica-texto-do-projeto-#74]
As aspas aparecem assim ``olá' ' no pdf do aluno. Além disso seguem ocorrendo erros no ambiente Para o professor devido a aspas estranhas. Exemplos Lição 1 Atividade 6 e Lição 2 Organizando as Ideias

**Comment by augustoteixeira** [comment]
O servidor está com alguns pacotes de fonte desatualizados. 
1. Acho perigoso fazer uma atualização do servidor tão perto da entrega
2. As aspas ficam corretas quando compilamos em casa pra entregar o material.

Então acho que vale a pena deixar dessa forma durante o piloto.
