### ISSUE TITLE
Exigir e-mail nos Comentários externos  da DokuWiki

### ISSUE THREAD

**Issue by simas0** [simas0/Livro-Aberto-de-Matematica-texto-do-projeto-#77]
As pessoas colocam comentários, mas não preenchem seus nomes ou e-mails. Se forem colaboracoes originais não poderemos aproveitar do modo como está.

**Comment by augustoteixeira** [comment]
O único jeito de fazer isso é permitir que somente usuários cadastrados façam comentários. Pode ser?

**Comment by simas0** [comment]
não.
Deixa pra lá. Vi que os comentários vem sem nomes nos e-mails, mas na
plataforma estão os nomes. Imagino que também colocaram os e-mails.
Em 11/07/2016 11:21, "gutosurrex" notifications@github.com escreveu:
