### ISSUE TITLE
Enviar e-mail sobre comentário respondido ao autor do comentário

### ISSUE THREAD

**Issue by simas0** [simas0/Livro-Aberto-de-Matematica-texto-do-projeto-#78]
Seguir mensagem parece não estar funcionando.

**Comment by augustoteixeira** [comment]
As notificações não estão funcionando diretamente do pacote. Eu tive que implementar eu mesmo um sistema de notificação. Com o sistema atual, todos podem seguir essas notificações ao se inscrever no grupo:
https://groups.google.com/d/forum/um-livro-aberto

Isso resolve o problema?

**Comment by augustoteixeira** [comment]
Esse é o link para se inscrever:
https://groups.google.com/forum/#!forum/um-livro-aberto/join

**Comment by simas0** [comment]
Agora está funcionando o "Acompanhar comentários" na plataforma.
