### ISSUE TITLE
Fazendo referências

### ISSUE THREAD

**Issue by hjbortol** [simas0/Livro-Aberto-de-Matematica-texto-do-projeto-#79]
Neste processo de revisão, atividades estão sendo incluídas e removidas. Assim, as referências digitadas têm que ser revistas (uma atividade de número 16, por exemplo, pode virar 17). Existe um mecanismo de fazer referências, como no LaTeX, que são robustas por mudanças de ordem?

@simas0

**Comment by simas0** [comment]
Pois é, isso tem que ser implementado logo. Coloco Crítico para mostrar que é mais que prioritário no momento.

**Comment by simas0** [comment]
A solução para esta etapa será a seguinte 
`Veja a Atividade 8 da Lição 1 <hidden [[cap1:secoes:ativ_hexag|(link)]]></hidden>`

Precisamos escrever manualmente o número da atividade e da lição porque a conversão da referência para o pdf não será implementada no momento.

Atenção: quando a atividade for movida para outra lição ou outra posição dentro da mesma lição, teremos que mudar o número da atividade ou da lição manualmente, o link não é necessário.

**Comment by simas0** [comment]
Mudei a prioridade porque não é mais fundamental para a entrega do livro de frações.

**Comment by simas0** [comment]
Desculpe, a solução acima não funciona. O `<hidden [[cap1:secoes:ativ_hexag|(link)]]></hidden>` some do pdf, mas cria uma nova linha no html, o que inviabiliza sua implementação. 

Precisamos de uma solução, do contrário vai haver referências erradas e teremos dificuldade de descobrir qual é a certa e até mesmo dificuldade para decidir se está errada ou não. Veja o "Para o professor" no preâmbulo da Lição 4. Está cheio de referências às atividades daquela lição.

Devolvo a prioridade.

**Comment by hjbortol** [comment]
Estou revisando as sugestões dadas e, nos comentários, estão aparecendo numerações que não são mais válidas, porque atividades foram incluídas e excluídas.  É preciso pensar em um esquema melhor de referência.

**Comment by augustoteixeira** [comment]
Olá a todos, concordo que do jeito que está não dá pra ficar pra próxima etapa. Mas a prioridade agora é terminar frações.

Por hora, eu coloquei pra funcionar a referência normal da wiki `[[cap1:secoes:ativ_hexag|Atividade 3]]`. Veja por exemplo o preâmbulo da Lição 4.

Vou fechar esse issue, mas fica o lembrete que temos que automatizar a numeração dos links para a próxima fase.
