### ISSUE TITLE
Enumeração reinicia no pdf por espaço vertical na Atividade 1 da Lição 2

### ISSUE THREAD

**Issue by simas0** [simas0/Livro-Aberto-de-Matematica-texto-do-projeto-#83]
O espaço vertical é necessário e a enumeração funciona bem no html, mas no pdf funfa.

**Comment by augustoteixeira** [comment]
Feito. Agora vocês tem que trocar todos os
`==== - Atividade ====`
por
`==== Atividade - ====`
E parar de usar hífens cercados por espaços em branco nos títulos.
