### ISSUE TITLE
Subenumeração estraga no pdf (Atividade 2 da Lição 2)

### ISSUE THREAD

**Issue by simas0** [simas0/Livro-Aberto-de-Matematica-texto-do-projeto-#84]
No html está bom e é assim:

 a. Como dividir as três tortas de modo que cada amigo receba a mesma quantidade de torta? Faça um desenho no seu caderno mostrando sua proposta de divisão. Indique qual parte é de qual amigo!
b. Considerando-se uma torta, como você nomearia, usando frações, a quantidade de torta que: 
       I. Amarildo recebeu? 
       II. Amarildo e Beto receberam juntos? 
       III. Amarildo, Beto e Carlos receberam juntos? 
       IV. Amarildo, Beto, Carlos e Davi receberam juntos?
       V. Amarildo, Beto, Carlos, Davi e Edilson receberam juntos?
  c. A quantidade de torta que cada amigo recebeu é menor do que um quinto de torta? E do que dois quintos de torta? Explique sua resposta.
 d. A quantidade de torta que cada amigo recebeu é maior do que três quintos de torta? E do que quatro quintos de torta? Explique sua resposta.

**Comment by augustoteixeira** [comment]
Olá Fábio, duas coisas:

1) Havia um erro no conversor que agora foi corrigido.

2) A notação estava incorreta para sub-enumerações. Elas devem ter exatamente quatro espaços como abaixo:
https://www.umlivroaberto.com/livro/doku.php?id=cap2:secoes:explorando:papel:tortas:salgadas&do=diff&rev2%5B0%5D=1470087585&rev2%5B1%5D=1470665941&difftype=sidebyside

Abraços
