### ISSUE TITLE
Texto da Lição 4 em itálico no pdf do professor

### ISSUE THREAD

**Issue by simas0** [simas0/Livro-Aberto-de-Matematica-texto-do-projeto-#86]
A partir da Atividade 3 da Lição 4 todo o texto está em itálico. Parece que foi algum problema com a tabela. Não fo ium simples esquecimento de fechar um itálico aberto.

**Comment by augustoteixeira** [comment]
Era um link feito do jeito errado:

https://www.umlivroaberto.com/livro/doku.php?id=cap4:secoes:preencha_fita&do=diff&rev2%5B0%5D=1468811900&rev2%5B1%5D=1468845933&difftype=sidebyside
