### ISSUE TITLE
Incluir nomes das alunas da UFF como colaboradoras

### ISSUE THREAD

**Issue by hjbortol** [simas0/Livro-Aberto-de-Matematica-texto-do-projeto-#92]
@simas0, por favor, inclua os nomes das alunas da UFF:

Andreza Gonçalves – estudante da UFF
Bruna Luiz Luiza Oliveira – estudante da UFF
Tahyz Pinto – estudante da UFF

**Comment by simas0** [comment]
Feito!
https://www.umlivroaberto.com/wp/?page_id=53
