### ISSUE TITLE
O PDF da Lição 4 do aluno estã com 51805 páginas!

### ISSUE THREAD

**Issue by hjbortol** [simas0/Livro-Aberto-de-Matematica-texto-do-projeto-#93]
![licao-4-51805-paginas](https://cloud.githubusercontent.com/assets/7694624/18007747/b2f3fc9c-6b7b-11e6-858a-d2f9c748cb6e.jpg)

**Comment by augustoteixeira** [comment]
Jesus!!! Óbvio que isso tinha que acontecer logo antes da entrega, né?

Eu acho que o problema está com a figura tab_cores que é maior que uma página inteira... mas não tenho certeza.

Nesse exato momento, temos que focar na entrega e o pdf está compilando bem fora da plataforma. Coloquei ele aqui:
https://www.umlivroaberto.com/pdf/final_cap4_aluno.pdf
vamos deixar do jeito que está por hora.
