### ISSUE TITLE
Dokuwiki não mostra figuras em svg

### ISSUE THREAD

**Issue by simas0** [simas0/Livro-Aberto-de-Matematica-texto-do-projeto-#96]
Na atividade [https://www.umlivroaberto.com/livro/doku.php?id=cap1:secoes:ativ_retangulos_coloridos] incluí o arquivo cap1:secoes:ativ_retangulos_coloridos_resposta1.svg, mas obtenho uma mensagem de erro no local da figura na página quando salvo.

**Comment by hjbortol** [comment]
Aqui está a entrada SVG na Wikipédia: 
https://en.wikipedia.org/wiki/Scalable_Vector_Graphics

**Comment by augustoteixeira** [comment]
Acho que agora está funcionando:
https://www.umlivroaberto.com/livro/doku.php?id=sandbox
