### ISSUE TITLE
Qual é o formato ideal para se colocar as figuras feitas em tikz na versão digital?

### ISSUE THREAD

**Issue by simas0** [simas0/Livro-Aberto-de-Matematica-texto-do-projeto-#97]
Estou usando .png exportados do pdf ou após printscreen do pdf. A qualidade está ruim. O melhor seria realmente usar o formato svg?

**Comment by hjbortol** [comment]
Sim, pois o formato SVG é vetorial e não perde qualidade!

**Comment by simas0** [comment]
Então temos um problema porque não consigo que sejam exibidas figuras em svg na plataforma.

https://github.com/simas0/Livro-Aberto-de-Matematica-texto-do-projeto-/issues/96

**Comment by augustoteixeira** [comment]
Você fechou porque resolveu sozinho?

Eu acho que png com qualidade um pouco melhor também seria aceitável. No html, normalmente o que acontece é que as pessoas colocam uma figura de qualidade razoável (ou seja que não pode ser distinguida de uma vetorial em uma tela de computador ou tablet).

Pra impressão a qualidade tem que ser bem melhor, pois temos por volta de dez vezes mais pontos por polegada quadrada no papel que na tela.
