### ISSUE TITLE
Aspas estragam com compilação XeLatex

### ISSUE THREAD

**Issue by simas0** [simas0/Livro-Aberto-de-Matematica-texto-do-projeto-#99]
Exemplo no refletindo da Lição 1 e refletindo da Lição 4. Em outros lugares parece que está direito. Pretendo levar para impressão por volta das 13h desta segunda.

**Comment by simas0** [comment]
O arquivo atual é o livro_aluno.tex os demais estão desatualizados, exceto o cap5_aluno.tex

**Comment by augustoteixeira** [comment]
Feito, com uma pequena mudança no template.sty.
